// packages/core/src/__fixtures__/vue-fixture/Card.vue
<template>
  <div class="px-4 mt-[13px] text-blue-500 bg-[#ff5733]" :style="{ padding: '11px', color: '#ff0000' }">
    <p style="margin: 7px; font-size: 15px">Hello</p>
    <span :class="{ 'rounded-[7px]': isRound }">World</span>
  </div>
</template>

<script setup>
const isRound = true;
const color = '#ff0000'; // script content is never checked
</script>

<style>
.btn { color: #00ff00; padding: 99px; }
</style>

<style lang="scss">
.card {
  $bg: #1a1a2e;
  background: $bg;
  padding: 88px;
  .inner { margin: 77px; }
}
</style>

// packages/core/src/__fixtures__/svelte-fixture/Card.svelte
<script>
  let isActive = true;
  let count = 0;
</script>

<style lang="scss">
  .container {
    $border: #333;
    border-color: $border;
    padding: 13px;
    .title { font-size: 15px; }
  }
</style>

<div class="container px-4 mt-[13px] bg-[#ff5733]"
     style="border-radius: 7px">
  <h1 style:color="#ff0000"
      style:padding="9px"
      class:rounded-[3px]={isActive}>
    Hello
  </h1>
  {#if count > 0}
    <span class="text-[11px]">Count: {count}</span>
  {/if}
</div>
